### ISSUE TITLE
Counting one too many clusters?

### ISSUE THREAD

**Issue by jdd112** [mhahsler/dbscan#10]
Running DBScan with MinPts=1 and eps = 50 on the attached data returns 11 clusters, i am expecting 10 clusters ... am i missing something?

Column A is X Data, Column B is Y Data.  Please note this data is always organized smallest to largest and the Y Data is always 1.

Please look at tab 42127348110000, i have added tab 42127348110000-manual clusters to show my assumptions for clusters.  

I am running R as follows:  

	data <- read.csv(file.names[i])
	res <- dbscan(data, eps=50, MinPts = 1
[42041320940000.xlsx](https://github.com/mhahsler/dbscan/files/804251/42041320940000.xlsx)
)

thanks.

**Comment by peekxc** [comment]
Perhaps there is something right with the file linked, but could you clarify the question a bit? 

Running dbscan with the first two columns of your data results in 32 clusters with 0 noise points for me: 

```
data <- read.csv("~/Downloads/42041320940000.csv")
data <- apply(as.matrix(na.omit(data))[, 1:4], 2, as.numeric)
res <- dbscan(data, eps=50, minPts = 1)
```
After converting the spreadsheet to csv. Looking at the spreadsheet attached, there are a number of things I notice immediately: 

- dimensions 3 and 4 are blank for record 1 
- dimension 4 is blank for record 2
- There's a random 'x' character for dimension 5 at record 19, I assume this was unintentional? 

I used second statement (apply) removes this data and cleans the data set, as dbscan expects a numeric matrix as input. 

In your comments, you only mentioned dimensions A and B as the data. What about dimensions C and D? Also, may I ask why you are expecting 11 clusters?

**Comment by jdd112** [comment]
I apologize for the confusing excel document i have clarified it in the most recent version.  I think the cluster count should be 29.  I am mirroring the logic in Columns C & D.  Column c calculates the distance to the next point and column d counts the clusters when these points are more than 50 away.  could you please look this over and see if i am missing something?
[Copy of 42041320940000.xlsx](https://github.com/mhahsler/dbscan/files/804409/Copy.of.42041320940000.xlsx)

**Comment by peekxc** [comment]
DBSCAN does 29 clusters with 0 noise. 
```
data <- read.csv("~/Documents/Copy.of.42041320940000.csv")
res <- dbscan(as.matrix(data[, 1:2]), eps=50, minPts = 1) # also works with just column 1
res 
```

> res
DBSCAN clustering for 191 objects.
Parameters: eps = 50, minPts = 1
The clustering contains 29 cluster(s) and 0 noise points.
...

It matches your fourth column as well
```
all(res$cluster == data[, 4]) # true 
```

**Comment by jdd112** [comment]
yup, you are right ... I had max(res$cluster)+1 on my output ... so sorry to waste your time.  Great work on this project.
