### ISSUE TITLE
 Issue with predicting cluster labeling, using DBSCAN object and Gower distance matrix for new data in R

### ISSUE THREAD

**Issue by ankhnesmerira** [mhahsler/dbscan#14]
Hi there, I'm having issue with predicting cluster labeling for a test data, based on a dbscan clustering model on the training data. I used gower distance matrix when creating the model:
```
> gowerdist_train <- daisy(analdata_train,
                   metric = "gower",
                   stand = FALSE,
                   type = list(asymm = c(5,6)))
```

Using this gowerdist matrix, the dbscan clustering model created was:
`> sb <- dbscan(gowerdist_train, eps = .23, minPts = 50)`

Then I try to use predict to label a test dataset using the above dbscan object:
`> predict(sb, newdata = analdata_test, data = analdata_train)`

But I receive the following error:

>   Error in frNN(rbind(data, newdata), eps = object$eps, sort = TRUE,
>   ...) :    x has to be a numeric matrix

I can take a guess on where this error might be coming from, which is probably due to the absence of the gower distance matrix that hasn't been created for the test data. My question is, should I create a gower distance matrix for all data (datanal_train + datanal_test) separately and feed it into predict? how else would the algorithm know what the distance of test data from the train data is, in order to label?
In that case, would the newdata parameter be the new gower distance matrix that contains ALL (train + test) data? and the data parameter in predict would be the training distance matrix, gowerdist_train?
What I am not quite sure about is how would the predict algorithm distinguish between the test and train data set in the newly created gowerdist_all matrix?
The two matrices (new gowerdist for all data and the gowerdist_train) would obviously not have the same dimensions. Also, it doesn't make sense to me to create a gower distance matrix only for the test data because distances must be relative to the test data, not the test data itself?
It hasn’t been very clear in the dbscan documentation how to use the predict function for distance matrix data (as opposed to raw data)

tried using gower distance matrix for all data (train + test) as my new data and received an error when fed to predict:

```
> gowerdist_all <- daisy(rbind(analdata_train, analdata_test),
                         metric = "gower",
                         stand = FALSE,
                         type = list(asymm = c(5,6)))
```
`> test_sb_label <- predict(sb, newdata = gowerdist_all, data = gowerdist_train)`

> ERROR: Error in 1:nrow(data) : argument of length 0 In addition: Warning message: In rbind(data, newdata) : number of columns of result is not a multiple of vector length (arg 1)

**Comment by peekxc** [comment]
I'm unable to reproduce the problem with the following test data: 

```
library("dbscan")
data("moons")
dist_moons <- cluster::daisy(moons, metric = "gower", stand = FALSE)
model <- dbscan(dist_moons, eps = .23, minPts = 50)
predict(model, newdata = moons[1:5,], data = moons)
```

To answer one of your question, inspection of dbscan's predict method reveals what it does; using the original parameters you passed into the dbscan function, the predict method will recomputes the nearest neighbors at the given radius `eps' for all the data points (train and test), then assigns the new points to their corresponding clusters.   

If you can attach the data you're working with or (if it's private data) attach a reproducible example set of data, I can further help you along. 

I also may be misunderstanding the issue.

**Comment by mhahsler** [comment]
`predict` defaults to Euclidean distance and so does Gower's distance for only numeric attributes. Here is an example that breaks predict because it also uses species for clustering:

```
data(iris)
d <- cluster::daisy(iris, metric = "gower", stand = TRUE)
model <- dbscan(d, eps = .23, minPts = 50)
predict(model, newdata = iris[1:5,], data = iris)

Error in frNN(rbind(data, newdata), eps = object$eps, sort = TRUE, ...) : 
  x has to be a numeric matrix. 
```

I am not sure how to fix this, but I guess we need to pass on some sort of distance (or distance function to be used) between newdata and data.
