### ISSUE TITLE
unrecognized parameters in OPTICS function

### ISSUE THREAD

**Issue by jdonager** [mhahsler/dbscan#15]
I was using package version 0.9.8 without issue. After upgrading, it appears that with both 1.0 and 1.1 I am confronted with the same error when using the OPTICS function:
simpleError in optics(layer[, 1:2], eps = 10, eps_cl = epc, minPts = mp, xi = 0.05): Unknown parameter: eps_cl, xi
Furthermore, when I leave out those parameters I get an optics object, but the optics_cut function is not recognized. I have replicated this on a windows and a linux machine. Has anyone else encountered this?

**Comment by jdonager** [comment]
The function works as expected with version 0.9.8

**Comment by peekxc** [comment]
The API changed after 0.9.8 to try to make the process of extracting clusters a bit a cleaner and more clear cut, as mentioned in the [news feed](https://github.com/mhahsler/dbscan/blob/master/NEWS.md). See ?dbscan::optics for more details on the current API. 

You can get flat clusters with the following extraction  
```
library("dbscan")
data("iris")
x <- as.matrix(iris[, 1:4])
opt <- optics(x, eps = 1, minPts = 4)
opt <- extractDBSCAN(opt, eps_cl = .4)
```

OPTICS fundamentally gives an ordering of the data set which is post-processed to extract clusters. In the 'cutting' case, one specifies a reachability threshold to cut the reachability ordering at, and that is used to determine the clustering. That method is shown above. The OPTICS 'Xi' method is an alternative way to extracting a _hierarchical_ clustering from the OPTICS object. 

```
opt <- extractXi(opt, xi = .05)
```

It does not make sense to use the xi and eps_cl parameter at the same time. 

I apologize for any regressive errors this may have caused. For more details on the difference between these two clustering algorithms, please see the original OPTICS paper by Ankerst et. al.

**Comment by jdonager** [comment]
Thank you for the clarification, I am still learning about this method and
didn't fully understand the difference.
Part of the confusion came from the optics_cut function no longer working,
and trying to figure out a way around that.
Cheers

**Comment by jdonager** [comment]
When only one of the parameters is used in the function (eps_cl), I still
get the same error, despite the documentation for the function showing that
it can be included. Is that just not a possibility anymore?

**Comment by peekxc** [comment]
Correct, it is not a possibility anymore to pass the eps_cl directly via the OPTICS function. 

The documentation groups up the two extraction methods within the same help page for simplicity. If you look at the definition of the optics function: 

`optics(x, eps, minPts = 5, ...)`

And the description of the parameters corresponding to those parameter settings (x, eps, minPts, and ...), you will see there is no mention of cluster extraction. 

Similarly, the only function containing the parameter 'eps_cl' is the `extractDBSCAN` function.

**Comment by jdonager** [comment]
Ok,
Thank you so much for your help.

On Tue, May 16, 2017 at 10:45 AM, Matt Piekenbrock <notifications@github.com
