### ISSUE TITLE
install error within  ios system 

### ISSUE THREAD

**Issue by ustchqh** [mhahsler/dbscan#19]
> install_github("mhahsler/dbscan")
Downloading github repo mhahsler/dbscan@master
Installing dbscan
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/n9/hh04k0tn79q9q501k2b4rbbw0000gn/T/RtmpLkatHj/devtools3b955cbbe805/mhahsler-dbscan-1d0a3ac'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 

* installing *source* package ‘dbscan’ ...
** libs
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c ANN.cpp -o ANN.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [ANN.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_JP.cpp -o R_JP.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_JP.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_dbscan.cpp -o R_dbscan.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_dbscan.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_density.cpp -o R_density.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_density.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_frNN.cpp -o R_frNN.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_frNN.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_kNN.cpp -o R_kNN.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_kNN.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_optics.cpp -o R_optics.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_optics.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c R_regionQuery.cpp -o R_regionQuery.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [R_regionQuery.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [RcppExports.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c bd_fix_rad_search.cpp -o bd_fix_rad_search.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [bd_fix_rad_search.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c bd_pr_search.cpp -o bd_pr_search.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [bd_pr_search.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c bd_search.cpp -o bd_search.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [bd_search.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c bd_tree.cpp -o bd_tree.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [bd_tree.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c brute.cpp -o brute.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [brute.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c buildHDBSCAN.cpp -o buildHDBSCAN.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [buildHDBSCAN.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c dendrogram.cpp -o dendrogram.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [dendrogram.o] Error 127 (ignored)
gcc -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c init.c -o init.o
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_dump.cpp -o kd_dump.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_dump.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_fix_rad_search.cpp -o kd_fix_rad_search.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_fix_rad_search.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_pr_search.cpp -o kd_pr_search.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_pr_search.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_search.cpp -o kd_search.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_search.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_split.cpp -o kd_split.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_split.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_tree.cpp -o kd_tree.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_tree.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c kd_util.cpp -o kd_util.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [kd_util.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c mrd.cpp -o mrd.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [mrd.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c perf.cpp -o perf.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [perf.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c prims_mst.cpp -o prims_mst.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [prims_mst.o] Error 127 (ignored)
I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"      -c union_find.cpp -o union_find.o
/bin/sh: I/Library/Frameworks/R.framework/Resources/include: No such file or directory
make: [union_find.o] Error 127 (ignored)
-dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -L/usr/local/lib -o dbscan.so ANN.o R_JP.o R_dbscan.o R_density.o R_frNN.o R_kNN.o R_optics.o R_regionQuery.o RcppExports.o bd_fix_rad_search.o bd_pr_search.o bd_search.o bd_tree.o brute.o buildHDBSCAN.o dendrogram.o init.o kd_dump.o kd_fix_rad_search.o kd_pr_search.o kd_search.o kd_split.o kd_tree.o kd_util.o mrd.o perf.o prims_mst.o union_find.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/bin/sh: -dynamiclib: command not found
make: *** [dbscan.so] Error 127
ERROR: compilation failed for package ‘dbscan’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/dbscan’

**Comment by mhahsler** [comment]
I cannot reproduce this error using Ubuntu. Looks like the problem is your Rcpp installation.
