### ISSUE TITLE
LOF return Nan values

### ISSUE THREAD

**Issue by isamsing** [mhahsler/dbscan#2]
I have been using LOF for analysing more than 10,000 data point. However, the lof function in dbscan package return nan value.

**Comment by mhahsler** [comment]
Can you share a (small) dataset that produces NAN values with me?

**Comment by isamsing** [comment]
Hello Micheal,
Thank for looking into the issue. I have attached the .csv file with this email.
Regards,Samneet Singh

Date: Thu, 31 Mar 2016 09:25:12 -0700

**Comment by mhahsler** [comment]
I seem to not be able to see your attachment. Can you email it directly to me at michael at hahsler.net?

**Comment by mhahsler** [comment]
The problem was that the data has more than k duplicate points. The new version returns now 1 instead of NaN. However, the LOF paper suggests to first remove duplicates before running LOF.
