### ISSUE TITLE
Weights in dbscan()

### ISSUE THREAD

**Issue by EmmanuelGustin** [mhahsler/dbscan#23]
Hi, 
Changing back from my comment earlier. Some of the unexpected behavior that I saw was due to bugs in my own code -- a good thing!
Still one thing remains that I find odd: Using uniform random weights does improve clustering... at least in my data set.
But the issue can be closed!

**Comment by mhahsler** [comment]
I am glad to hear that it is not a problem on our end!

About the random weights: What you do is basically "soft" sampling, meaning that you randomly remove weight from some data points. This effectively has a similar effect as increasing minPts and maybe that is what drives what you see.
