### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by vikashkr117** [mhahsler/dbscan#3]
The link to download and install is not working for me. I used -
install.packages("dbscan")

http://cran.rstudio.com/bin/windows/contrib/3.2/dbscan_0.9-6.zip

**Comment by nithinsingh61** [comment]
@vikashkr117   Did you try mirror links ? can you be more specific about error  ?

**Comment by mhahsler** [comment]
The link above is obsolete. The version was pumped to 0.6-7 and install.packages should resolve this correctly. Please try again.

**Comment by vikashkr117** [comment]
Thank you!

**Comment by mkburak** [comment]
I'm also having an issue installing dbscan in R 3.0.3. For dbscan_0.9-7, install.packages as a source or binary package comes up with warnings/errors. Is there a simple compatibility issue I'm missing?

**Comment by mhahsler** [comment]
It installs for me fine under R 3.3.0 and all the checks on CRAN seem fine.  Please send me he output of sessionInfo().

**Comment by mkburak** [comment]
The problem was with me - didn't check how out of date R was on my lab computer. Thank you for the reply!

**Comment by kageazusa** [comment]
I tried to install dbscan but it failed. I updated R to version 4.1.3 (2022-03-10), but it didn't work. What is the problem? Should I downgrade R?

> > install.packages("dbscan")
>  --- このセッションで使うために、CRAN のミラーサイトを選んでください --- 
>  警告:  unable to access index for repository https://cran.ism.ac.jp/src/contrib:
>    URL 'https://cran.ism.ac.jp/src/contrib/PACKAGES' を開けません 
>  警告:  unable to access index for repository https://cran.ism.ac.jp/bin/macosx/contrib/4.1:
>    URL 'https://cran.ism.ac.jp/bin/macosx/contrib/4.1/PACKAGES' を開けません 
>  警告メッセージ: 
> package ‘dbscan’ is not available for this version of R
> 
> A version of this package for your version of R might be available elsewhere,
> see the ideas at
> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by mhahsler** [comment]
The message says that the CRAN mirror you are using is not available. Please try again and see if it was only a temporary outage. If not, then change the repository to a different one from this list: https://cran.r-project.org/mirrors.html

**Comment by kageazusa** [comment]
I changed the CRAN mirror and It worked. Thank you!
