### ISSUE TITLE
NA values on parameters in dbscan

### ISSUE THREAD

**Issue by ArthurPERE** [mhahsler/dbscan#34]
Hello,

I don't really know if it's a bug or not, but when I write this in R : 
```
dbscan::dbscan(cbind(
     x = runif(10, 0, 10) + rnorm(100, sd = 0.2),
     y = runif(10, 0, 10) + rnorm(100, sd = 0.2)
 ), eps = NA, minPts = NA)
```

R return this : 
```
DBSCAN clustering for 100 objects.
Parameters: eps = NA, minPts = NA
The clustering contains 18 cluster(s) and 0 noise points.

 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 
10  3 10  9  3 10  8  6 10  8  8  8  1  1  1  1  1  2 

Available fields: cluster, eps, minPts
```

But what does R or Rcpp do with the NA value, it is not infinite nor null, if it's calculate the value eps and minPts how do it calculated it and how can I extract it if  it nor a bug.

Thank you,
Arthur

**Comment by mhahsler** [comment]
This is a good observation. I just add checks to make sure that eps >=0 and minPts >=0 to avoid that undefined things happen.
