### ISSUE TITLE
DBSCAN with categorica/factor/dummy variables

### ISSUE THREAD

**Issue by akarlinsky** [mhahsler/dbscan#41]
Can DBSCAN be used in data with non-continuous variables? For example, a dummy for married (0 or 1) or a multi-level categorical variable for marital status (married, single, divorced, widowed etc.). If so, how? I get an error that "x has to be a numeric matrix".

**Comment by mhahsler** [comment]
If a data.frame is specified, then Euclidean distance is applied. You have to convert the data to all numeric values (e.g., via dummy encoding). Alternatively, you can precalculate a distance matrix using the appropriate distance measure and supply that to dbscan.
