### ISSUE TITLE
LOF fails after upgrading to dbscan 1.1-6

### ISSUE THREAD

**Issue by morchalabi** [mhahsler/dbscan#45]
This command previously would work now it fails:

`dbscan::lof(x = dt, k = 3, sort = F, approx = 1.1)`
`Error in kNN(x, k, sort = TRUE, ...) : 
  formal argument "sort" matched by multiple actual arguments`

**Comment by mhahsler** [comment]
Thank you for the report. sort is now more efficient and internally always set to TRUE for lof. I have now added this to the man page. Note: this does not change the order of the output of lof. Please remove sort = F from your code. lof needs some more improvements and I will check for the next release if time can be saved by not sorting the k-nearest neighbors.

**Comment by morchalabi** [comment]
Thanks. Are you @mhahsler sure setting sort = T does not slow down run time for big datasets?
