### ISSUE TITLE
kNN crashing (segfault) when matrix has Inf values

### ISSUE THREAD

**Issue by yonatans2** [mhahsler/dbscan#47]
The kNN function gave me a segmentation fault when some of the values were infinite. This was fixed by capping the numbers calculated. Apologies for not reproducing the data/code...

Best,
Yonatan

**Comment by mhahsler** [comment]
I just checked with some data where I set some values to Inf, but I could not replicate the problem. A small sample of your data would be helpful. Do you use a data.frame or distances as input?
