### ISSUE TITLE
Error in mrd(x_dist, coredist) :    number of mutual reachability distance values and size of the distances do not agree.

### ISSUE THREAD

**Issue by powerhorse1986** [mhahsler/dbscan#50]
Hi,

I am using this package doing some research on a data set. It's a matrix which has 50970 rows and 18 columns. When I was running the function hdbscan with default settings, an error was raised which said "Error in mrd(x_dist, coredist) : 
  number of mutual reachability distance values and size of the distances do not agree." 

Would you please suggesting how to fix this error? Thanks in advance.

Li

**Comment by mhahsler** [comment]
Hi, thank you for the report. Please confirm that you are running the latest version from CRAN and send me an example that replicates the issue.

Thanks,
Michael

**Comment by mhahsler** [comment]
I found the issue in the GitHub version. It should be fixed now.

**Comment by schamaille** [comment]
Hi, 

I am having the same error as reported by @powerhorse1986, with the latest CRAN version as well as with the development version downloaded on github. Is this more likely to be a bug or an issue with the dataset (size or whatever)? My dataset (~64000 rows * 2 columns) seems 'correct' (nothing unusual spotted, it's the results of a umap).

Any suggestions welcomed. Thanks

simon

**Comment by mhahsler** [comment]
Hi,  I cannot replicate the issue. Can you send me the data/code to replicate the issue with the CRAN version?

**Comment by schamaille** [comment]
Hi,
thanks for taking the time. You can download the rds file here (10Mo):

https://filedn.eu/lW33td8UP2NVASIrbOnyn80/umap.rds

and this code replicates the issue with the latest CRAN version:

library(dbscan)
umap <- readRDS("umap.rds")
foo <- hdbscan(umap$layout,minPts=1000)

Error in mrd(x_dist, coredist) :
   number of mutual reachability distance values and size of the 
distances do not agree.

simon


-- 
--
§-------------------------------------------------------§
Simon Chamaillé-Jammes
CNRS, Centre d'Ecologie Fonctionnelle et Evolutive
1919 route de Mende, 34293 Montpellier Cedex, France
Tel (+33)(0)467613218 / Fax (+33)(0)467410616
Email: ***@***.***
Twitter: @chamaillejammes
Websites:
http://simonchamaillejammes.strikingly.com/
https://www.sangliers.cnrs.fr/
https://www.deepfaune.cnrs.fr/
ORCID: 0000-0003-0505-6620
§-------------------------------------------------------§

§ Life is what happens while we make other plans

**Comment by mhahsler** [comment]
I can reproduce the error with the CRAN version which does not support long vectors.

The version on GitHub runs your code on my machine without an error:
```
HDBSCAN clustering for 64751 objects.
Parameters: minPts = 1000
The clustering contains 2 cluster(s) and 131 noise points.

    0     1     2 
  131 27403 37217 

Available fields: cluster, minPts, coredist, cluster_scores,
                  membership_prob, outlier_scores, hc

```
