### ISSUE TITLE
DBSCAN for trajectories

### ISSUE THREAD

**Issue by kageazusa** [mhahsler/dbscan#51]
I would like to analyze trajectories (x, y, t) with multiple values of x and y. First I tried scikit-learn on Python (like this QA: https://stackoverflow.com/questions/52926477/run-dbscan-on-trajectories) but it turned out that we cannot do DBSCAN of multiple x and y values in scikit-learn (only x or y, or single x and single y would work).
With R, I attempted to do DBSCAN with below data, but it required a matrix.

> data <- list(list(c(0, 1), c(0, 1)), list(c(1, 1), c(1, 1)), list(c(1, 3), c(1, 3)))

Is it possible to do DBSCAN for multiple x and y values with your package? If possible, how can I input the data?
Like
x1, x2, x3, ..., y1, y2, y3, ... without correspondence of x and y? (Hopefully there should be a correspondence of x and y...)

**Comment by mhahsler** [comment]
If all your trajectories have the same length then you would just create a matrix where each row has all the x and y values of the points defining the trajectory.

**Comment by kageazusa** [comment]
Thank you! Let me ask you additional questions:
1) Is it the same to treat the data as {(x1, y1), (x2, y2) ..., (xn, yn)} and as (x1, x2, ..., xn, y1, y2, ..., yn) in the context of DBSCAN? Your answer is the latter case, but I'm not sure if they are identical.
2) What if I would like to analyze trajectories with different lengths? Does a matrix with NA work? (e.g. trajectory 1: length 5, trajectory 2: length 3 -> Can I fill the tail of the row of trajectory 2 with NA?)

**Comment by mhahsler** [comment]
Different lengths are an issue and NAs will not work. The best solution would be to calculate a distance matrix between the trajectories using the appropriate approach (see e.g., https://zheng-kai.com/paper/vldbj_2019.pdf) and then do dbscan on that distance matrix.

**Comment by kageazusa** [comment]
Thank you very much. I will look over the paper!
