### ISSUE TITLE
may you clarify is multi-density clustering  is implemented, since it is mentioned on references  ?

### ISSUE THREAD

**Issue by Sandy4321** [mhahsler/dbscan#53]
may you clarify is multi-density clustering  is implemented, since it is mentioned on references  ?

@inproceedings{ghanbarpour2014exdbscan,
 title={EXDBSCAN: An extension of DBSCAN to detect clusters in multi-density datasets},
 author={Ghanbarpour, Asieh and Minaei, Behrooz},
 booktitle={Intelligent Systems (ICIS), 2014 Iranian Conference on},
 pages={1--5},
 year={2014},
 organization={IEEE}
}

**Comment by mhahsler** [comment]
dbscan does not implement EXDBSCAN. Please read the paper or reach out to the authors.
