### ISSUE TITLE
Add broom tidier methods

### ISSUE THREAD

**Issue by joeroe** [mhahsler/dbscan#55]
Hello, thank you for this very helpful package.

Would you be open to a pull request adding [broom tidier methods](https://broom.tidymodels.org/articles/broom.html#tidying-functions) for dbscan and hdbscan objects?

**Comment by mhahsler** [comment]
Yes, definitely. An important thing is that the dependencies of dbscan do not get expanded. Suggests would be fine.

**Comment by joeroe** [comment]
Great, I'll do that.

You wouldn't have to have a dependency on broom, but the [recommended approach](https://www.tidymodels.org/learn/develop/broom/) involves importing and re-exporting the generic functions from the [generics](https://cran.r-project.org/web/packages/generics/index.html) package (which is designed to be as light a dependency as possible).

It looks like it might be possible to only have generics as a `Suggests` using [this trick](https://community.rstudio.com/t/write-s3-methods-for-generics-from-other-packages-without-importing-that-package/8884/4), but if it were me I'd prefer the extra  `Depends` over messing with the namespace on load? Up to you of course.

**Comment by mhahsler** [comment]
I agree and think that importing generics is better.

**Comment by m-muecke** [comment]
Perhaps I don't understand correctly, but broom implements the transformation functions, i.e. there should never be a broom dependency in dbscan, but rather dbscan in broom, see the following example: https://github.com/tidymodels/broom/blob/HEAD/R/mclust-tidiers.R#L63. Since dbscan wrappers are not implemented yet in the broom package that would be an open topic. I don't see an open issue for that, but perhaps they're open for PRs in case this is relevant.

**Comment by mhahsler** [comment]
Good point. I will look into that.

**Comment by joeroe** [comment]
@m-muecke broom *used* to implement the transformation methods, but due the volume now [no longer accepts them](https://broom.tidymodels.org/articles/maintenance.html#guidelines).

**Comment by m-muecke** [comment]
Ah, my mistake. I must have missed that. But, the generics package seems very light with only importing from methods. Then there would always be the option to create an extension package for it like [broomstick](https://github.com/njtierney/broomstick) or [mixed.models](https://github.com/bbolker/broom.mixed). For clustering I don't believe there is one yet, but there is [tidyclust](https://tidyclust.tidymodels.org/) in case you look for tidymodels compatibility, which doesn't support dbscan though. On a related note there is support for dbscan in [mlr3cluster](https://github.com/mlr-org/mlr3cluster/).

**Comment by mhahsler** [comment]
I have added tidiers to the package. Check them out @joeroe

**Comment by mhahsler** [comment]
@m-muecke If you want to look at how to get integration with tidy clust, that would be great. I assume that since we have tidies, that should be possible now.
