### ISSUE TITLE
pkgdown website for package

### ISSUE THREAD

**Issue by m-muecke** [mhahsler/dbscan#64]
It would be great to generate package website hosted via GitHub pages so that references are easier
 to search etc. This GitHub Action would suffice: https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml if interested I can also assist with creating a PR

**Comment by mhahsler** [comment]
Hi Maximilian,

I currently use R-universe for this
https://mhahsler.r-universe.dev/dbscan 

It provides build services and renders vignettes and man pages. A big plus is that I do not have to maintain Github actions for all my packages.

-Michael

**Comment by m-muecke** [comment]
Ah, I missed that, lovely.
