### ISSUE TITLE
Request for integration of ST-DBSCAN algorithm for spatio-temporal clustering

### ISSUE THREAD

**Issue by MiboraMinima** [mhahsler/dbscan#79]
I would like to suggest integrating the [ST-DBSCAN](https://doi.org/10.1016/j.datak.2006.01.013) algorithm into this package. The ST-DBSCAN algorithm is an extension of the traditional DBSCAN algorithm, designed to cluster data in 3D space, which is particularly useful for spatio-temporal data such as GPS trajectories.

The primary difference between DBSCAN and ST-DBSCAN is the addition of a second epsilon parameter (eps2), which defines the minimal temporal distance required for a point to be considered part of the same cluster. This allows for more accurate clustering in cases where both spatial and temporal proximity are important.

Currently, there are no R packages that natively support the ST-DBSCAN algorithm. However, I found a raw implementation available [here](https://github.com/CKerouanton/ST-DBSCAN), which could potentially serve as a reference or starting point for integration into this package.

Would you be interested in integrating this algorithm into your package?

**Comment by mhahsler** [comment]
Hi,

Thank you for bringing this up. This looks like a very specialized application that should probably go into its own package (potentially based on code in `dbscan` to improve performance).

Best,
Michael

**Comment by MiboraMinima** [comment]
Hi Michael, thank you for your reply and your advice!

Best,
Antoine
